### ISSUE TITLE
Chrome doesn't let the geonames api get called anymore when running over HTTP

### ISSUE THREAD

**Issue by nickytonline** [pushpickup/pushpickup#160]
@stewartmccoy, whenever we get back to pushpickup, we should look at this. I'm assuming the Geonames API is offered over HTTPS as well.

Chrome doesn't let the geonames api get called anymore when running over HTTP.

[blocked] The page at 'https://pushpickup.com/' was loaded over HTTPS, but ran insecure content from 'http://api.geonames.org/findNearbyPlaceNameJSON?lat=45.496871399999996&lng=-73.567356&radius=5&cities=cities1000&style=medium&username=pushpickup': this content should also be loaded over HTTPS.

**Comment by nickytonline** [comment]
To test this locally, follow the steps documented here, http://differential.com/blog/proxy-ssl-traffic-to-meteor-for-development

**Comment by stewartmccoy** [comment]
@nickytonline are those steps listed on differential the ones we need to take to resolve the SSL issue? If so, I can try and do that.

**Comment by nickytonline** [comment]
@stewartmccoy, it's not the steps to resolve the issue. It's the steps to
do to run pushpickup locally over SSL to work on the issue.

**Comment by stewartmccoy** [comment]
@nickytonline got it. This isn't an urgent issue as I just want to deploy to meteor.com for now and test what I'm developing locally. We can resolve this when I get to a point where I'm ready to deploy to prod again.

**Comment by nickytonline** [comment]
Tested and deployed to PROD.
