### ISSUE TITLE
Add game crashes on server-side if there is no user logged on

### ISSUE THREAD

**Issue by nickytonline** [pushpickup/pushpickup#164]
@stewartmccoy, I noticed this issue while testing the upgrade to Meteor 1.0.2.1. When you add a game and the user is not logged on, the subscription to the recently played games crashes as there is no user to subscribe to recently played games. We just need to check to see if there is a user logged on or not before trying to subscribe to the recently played games.

The error occurs in publish.js when the parameters are being checked

    Meteor.publish("recently-played", function() {
        check(this.userId, String);
        ...
    })
    
Here's a sample error.

    I20150114-22:10:20.053(-5)? Exception from sub bgidfgt5f42TcKuE7 Error: Match error: Expected string, got object
    I20150114-22:10:20.054(-5)?     at checkSubtree (packages/check/match.js:159:1)
    I20150114-22:10:20.055(-5)?     at check (packages/check/match.js:32:1)
    I20150114-22:10:20.056(-5)?     at [object Object].Match.Optional.types [as _handler] (app/server/publish.js:18:3)
    I20150114-22:10:20.057(-5)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
    I20150114-22:10:20.058(-5)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:943:1)
    I20150114-22:10:20.059(-5)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
    I20150114-22:10:20.059(-5)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
    I20150114-22:10:20.060(-5)?     at packages/ddp/livedata_server.js:546:1
    I20150114-22:10:20.060(-5)? Sanitized and reported to the client as: Match failed [400]
    I20150114-22:10:20.061(-5)?

**Comment by stewartmccoy** [comment]
@nickytonline what are the steps I can take locally to reproduce this error?

Currently, if a user tries to add a game without logging in, an error state prompts the user to log in or sign up from the 'add game' screen.

**Comment by nickytonline** [comment]
@stewartmccoy, It's even before they click the [add game] button. Just loading http://localhost:3000/addGame if you're not logged in will result in a server side error. It's a simple fix. I should be able to fix this on the weekend.

**Comment by nickytonline** [comment]
To see the error just run ```meteor debug``` and then go to http://localhost:3000/addGame

**Comment by stewartmccoy** [comment]
@nickytonline yep! I noticed in the server console after I commented.

Also, I merged your upgrade into devel, and for whatever reason, I have untracked files: 

.meteor/.id
.meteor/platforms
.meteor/versions
lib/custom.bootstrap.import.less
lib/custom.bootstrap.less
lib/custom.bootstrap.mixins.import.less

Any idea why those are showing up? And what should I do about them?

**Comment by nickytonline** [comment]
@stewartmccoy, for the /lib/*.less files, they're generated by the nemo64:bootstrap package, but they should not be untracked. I know what happened. I forgot to add those files before my check-in... My bad. That also explains why the color was off for you. If you want to fix that right away, just add an import for /client/stylesheets/config.import.less in the custom.bootstrap.imports.less file. Otherwise, I'll do it tomorrow.

For the meteor files, I'll need to check.
