### ISSUE TITLE
Can't join a game as of Meteor 1.0 upgrade

### ISSUE THREAD

**Issue by nickytonline** [pushpickup/pushpickup#169]
When you try to join a game nothing happens. This can be seen in an existing game in PROD here, https://pushpickup.com/g/aBDeQ5ceiCd99qZuz . If you open the developer tools in Chrome or the equivalent tools in another browser, you will get the following error:

```Uncaught TypeError: Cannot read property 'split' of undefined```

The line causing the issue as pointed out by @dwinston is https://github.com/pushpickup/pushpickup/blob/a5dd293fec54510620fd1ccc76af543cfd450381/client/lib/game.js#L9 . ```path``` is undefined because the ```Router.current().path``` has been deprecated. Apparently the way to go now is ```Iron.Location.get().path``` (see https://github.com/EventedMind/iron-location).

So the join game functionality needs to be fixed, but a sweep of the code should be done as well to ensure that that the new way to get the path is updated in the entire application.

**Comment by stewartmccoy** [comment]
@nickytonline this works now, but I realized we have a similar issue with leaving a game. I'm going to dig in now and see if it's something I can fix based on your findings with joining a game.
