### ISSUE TITLE
Add player to recent list throws error

### ISSUE THREAD

**Issue by stewartmccoy** [pushpickup/pushpickup#174]
- Running `modulus project tail logs`
- Add new game
- tails logs: "Adding player to recent lost"
- console: "e.makeErrorType.r {error: 400, reason: "Must give one or more friends", details: undefined, message: "Must give one or more friends [400]", errorType: "Meteor.Error"…}"

**Comment by stewartmccoy** [comment]
@sgup hey sir, do you know what might be going on here?

**Comment by stewartmccoy** [comment]
@sgup no need to fix it, just wondering if you could provide some direction because you worked with this code last :)

**Comment by nickytonline** [comment]
@stewartmccoy I'll take a peek at this.

**Comment by nickytonline** [comment]
@stewartmccoy, I have a question about this bug. It appears to be an incomplete feature. The [Invite Friends] button loads up a dummy list of friends, e.g. Jimmy Fallon, https://github.com/pushpickup/pushpickup/blob/master/client/views/games/creategame/invite-previous-players/invite-previous-players.js#L17. When I add a new game, I get the same error as mentioned above. The reason it happens is that there are no friends in the InvitedList collection.

**Comment by stewartmccoy** [comment]
@nickytonline actually, as I think about it, we're not going to need this feature going forward because we're going to build in SMS notifications for new games, as well as for follower connections. Do you wanna remove this code? I can also probably do it.

**Comment by nickytonline** [comment]
@stewartmccoy, it's been removed.
