### ISSUE TITLE
Make sure how we get a path is updated in the entire application

### ISSUE THREAD

**Issue by stewartmccoy** [pushpickup/pushpickup#175]
Hey Nick, can you do a sweep of the app to ensure how we get a path is updated in the entire application?

Currently, 'Leave game' functionality is broken.

The new approach is `Iron.Location.get().path`. Check out [Iron Location docs](https://github.com/EventedMind/iron-location) for more info.

**Comment by nickytonline** [comment]
@stewartmccoy, when I fixed issue #169, I did a sweep of the application and updated how the path is retrieved everywhere via ```Iron.Location.get().path```. I'll close this and create an issue for the broken 'Leave game' functionality.
