### ISSUE TITLE
Add testing to the project

### ISSUE THREAD

**Issue by nickytonline** [pushpickup/pushpickup#179]
@stewartmccoy, to ensure stability of the code base, I propose we add testing. When testing in Meteor, Velocity is the way to go, http://velocity.meteor.com. This way, going forward we can add unit testing as well as e2e testing.

**Comment by stewartmccoy** [comment]
@nickytonline I'm keen on getting two major features in places and then adding testing. I think it's a great idea and I want to move that direction, but I also want to get user profiles and SMS game notifications working, as well as componentizing the style and cleaning up some of the markup.

Does that sound reasonable or are my priorities out of whack?

**Comment by nickytonline** [comment]
@stewartmccoy, as discussed, this wasn't to test the entire project, it was just to get testing in place. Going forward, we'll test new stuff and for old stuff, we'll add testing as we touch old code.

I've got this checked in on my ["integrating-velocity-testing-framework" branch](https://github.com/pushpickup/pushpickup/tree/integrating-velocity-testing-framework), but for now I'm not doing a PR because of this, https://github.com/meteor-velocity/html-reporter/issues/60 . Once that issue is resolved, I will create a PR for the devel branch.

**Comment by stewartmccoy** [comment]
@nickytonline sounds good. I need to read up on how it works :)
